### ISSUE TITLE
Dark theme not working properly for some PDFs

### ISSUE THREAD

**Issue by Oliver-Haynes** [shivaprsd/doqment#16]
![image](https://github.com/shivaprsd/doqment/assets/132023324/43913ccd-b76b-424f-8d4c-dabdab4c7137)
when trying to apply the firefox theme only the area behind the text changes,but when using the regular dark theme it works fine 
![image](https://github.com/shivaprsd/doqment/assets/132023324/457aea94-b87f-4694-8d4a-815ba6ece0e9)

**Comment by shivaprsd** [comment]
Hi @Oliver-Haynes, probably this PDF has a big white image behind the text. Can you attach the PDF, so that I can try to reproduce the issue?

**Comment by Oliver-Haynes** [comment]
> Hi @Oliver-Haynes, probably this PDF has a big white image behind the text. Can you attach the PDF, so that I can try to reproduce the issue? Thanks!

https://madasmaths.com/archive/iygb_practice_papers/fp2_practice_papers/fp2_w.pdf
not the same pdf but from the same place

**Comment by shivaprsd** [comment]
@Oliver-Haynes Yes, the PDFs from this location have a big all-white rectangular image (almost covering the page) behind the text (probably to include the vertical watermark on either sides). You can verify this by toggling the `Blend Images` option in the toolbar (click the ⚙️ icon near the theme name to reveal it), you can see it even in the light theme.

Some PDF apps create PDFs this way, which is sad, and the best we can do is to invert the image. But then it is nearly the same as using the "regular dark theme" (which actually is just inverting the page colours).

**Comment by shivaprsd** [comment]
@Oliver-Haynes Can we close this issue? It is possible to remove the watermark with any PDF editing tool. E.g. I used this online tool: https://products.aspose.app/pdf/remove-watermark, and here is the result, this PDF works fine in dark mode:

[RemoveWatermark_fp2_w.pdf](https://github.com/user-attachments/files/16432855/RemoveWatermark_fp2_w.pdf)

P.S. be careful to select *only* the watermark on either sides; otherwise it removes the figures in the centre also.
