### ISSUE TITLE
Incompatibility with Zotero Connector

### ISSUE THREAD

**Issue by kkensuke** [shivaprsd/doqment#7]
`doqment` is a very useful extension, but it seems it is incompatible with `Zotero Connector` for Firefox, that is, I can't save PDFs. I often use `Zotero Connector` to save PDFs from arXiv, so it would be great if I could use them simultaneously.

**Comment by shivaprsd** [comment]
Sorry to hear that.

Can you explain the problem a bit more? I don't know what `Zotero Connector` is. Is that another extension? How does *doqment* clash with it?

If you just want to download PDFs to your hard disk there is a button on the toolbar. But I don't think this is what you are aiming for.

**Comment by shivaprsd** [comment]
Firstly, thanks for introducing me a software I didn't know I needed. 😊

No, the problem is not just the change of URL. Extensions can't grab data from other extensions' pages (due to security reasons), so `Zotero Connector` disables itself on `doqment`'s viewer page. So simply reporting this issue there is likely to be dismissed as *wont-fix*.

The only workaround now is to bypass `doqment` altogether when intending to save the PDF to `Zotero`. Some ways I can think of:

1. Use `Save to Zotero` button directly on the arXiv page, without opening the PDF. This automatically saves both metadata and the PDF (recommended method by Zotero docs also).
2. Allow `Zotero Connector` to run in private tabs (extensions are disallowed by default); then right click on the PDF link to open it in a private window.
3. Download the file to disk and add manually (this sucks).

Tell me if both 1 and 2 above might be inconvenient to you.

**Comment by kkensuke** [comment]
> Use `Save to Zotero` button directly on the arXiv page, without opening the PDF. This automatically saves both metadata and the PDF (recommended method by Zotero docs also).

I should have noticed this earlier. It takes less time to save the PDF and its metadata than after opening the PDF. 😂

Thank you so much!
